name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10.30.3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run autofix
        run: pnpm lint:fix

      - name: autofix.ci
        uses: autofix-ci/action@v1.3.3
